[Numpad1]
input_path = '/dev/input/event6'

[Numpad1.macros]
KEY_KP0 = 'firefox http://duckduckgo.com'
KEY_KP1 = 'konsole -e htop'
KEY_KP2 = 'chromium-browser https://gmail.com'
KEY_KP3 = 'dolphin /home/rick/Nextcloud'

[Numpad1.macros.KEY_BACKSPACE]
KEY_KP0 = 'firefox http://github.com'
KEY_KP3 = 'firefox https://nextcloud.fmhmail.online:8443'

[Numpad1.macros.KEY_NUMLOCK]
KEY_KP0 = 'kioclient5 exec /home/rick/.local/share/applications/jetbrains-webstorm.desktop'
